service: bmad-odemo-students

custom:
  stage: ${opt:stage, self:provider.stage}
  resourcesStages:
    prod: prod
    dev: dev
  resourcesStage: ${self:custom.resourcesStages.${self:custom.stage}, self:custom.resourcesStages.dev}

provider:
  name: aws
  runtime: nodejs10.x
  stage: dev
  region: us-east-1

plugins:
  - serverless-webpack
  - serverless-offline
  - serverless-dotenv-plugin

functions:
  list-students:
    handler: functions/list.handler
    events:
      - http:
          method: get
          path: students
  get-student:
    handler: functions/get.handler
    events:
      - http:
          method: get
          path: students/{id}
